// export { first } from '@wareset-utilites/lang/first'
// export { includes } from '@wareset-utilites/lang/includes'
// export { indexOf } from '@wareset-utilites/lang/index-of'
// export { last } from '@wareset-utilites/lang/last'
// export { lastIndexOf } from '@wareset-utilites/lang/last-index-of'
// export { length } from '@wareset-utilites/lang/length'
// export { slice } from '@wareset-utilites/lang/slice'

export { array } from './array'
export { clear } from './clear'
export { filter } from './filter'

export { find } from './find'
export { findExtraLeft } from './find-extra-left'
export { findExtraRight } from './find-extra-right'

export { findIndex } from './find-index'
export { findIndexExtraLeft } from './find-index-extra-left'
export { findIndexExtraRight } from './find-index-extra-right'

export { forEach } from './for-each'
export { forEachExtraLeft } from './for-each-extra-left'
export { forEachExtraRight } from './for-each-extra-right'
export { forEachRight } from './for-each-right'

export { join } from './join'
export { map } from './map'
export { pop } from './pop'
export { push } from './push'
export { reverse } from './reverse'
export { shift } from './shift'

export { some } from './some'
export { someExtraLeft } from './some-extra-left'
export { someExtraRight } from './some-extra-right'

export { splice } from './splice'
export { spliceBetween } from './splice-between'
export { spliceWith } from './splice-with'
export { unshift } from './unshift'
