// export { prototype } from './prototype'
// export { toExponential } from './prototype/toExponential'
// export { toFixed } from './prototype/toFixed'
// export { toLocaleString } from './prototype/toLocaleString'
// export { toPrecision } from './prototype/toPrecision'
// export { toString } from './prototype/toString'
// export { valueOf } from './prototype/valueOf'

export { Number } from './Number'

export { EPSILON } from './EPSILON'
export { MAX_SAFE_INTEGER } from './MAX_SAFE_INTEGER'
export { MAX_VALUE } from './MAX_VALUE'
export { MIN_SAFE_INTEGER } from './MIN_SAFE_INTEGER'
export { MIN_VALUE } from './MIN_VALUE'
export { NaN } from './NaN'
export { NEGATIVE_INFINITY } from './NEGATIVE_INFINITY'
export { POSITIVE_INFINITY } from './POSITIVE_INFINITY'
export { isFinite } from './isFinite'
export { isInteger } from './isInteger'
export { isNaN } from './isNaN'
export { isSafeInteger } from './isSafeInteger'
export { parseFloat } from './parseFloat'
export { parseInt } from './parseInt'
