// export { default as prototype } from './prototype'
// export { default as toExponential } from './prototype/toExponential'
// export { default as toFixed } from './prototype/toFixed'
// export { default as toLocaleString } from './prototype/toLocaleString'
// export { default as toPrecision } from './prototype/toPrecision'
// export { default as toString } from './prototype/toString'
// export { default as valueOf } from './prototype/valueOf'

export { default as Number } from './Number'

export { default as EPSILON } from './EPSILON'
export { default as MAX_SAFE_INTEGER } from './MAX_SAFE_INTEGER'
export { default as MAX_VALUE } from './MAX_VALUE'
export { default as MIN_SAFE_INTEGER } from './MIN_SAFE_INTEGER'
export { default as MIN_VALUE } from './MIN_VALUE'
export { default as NEGATIVE_INFINITY } from './NEGATIVE_INFINITY'
export { default as POSITIVE_INFINITY } from './POSITIVE_INFINITY'
export { default as isFinite } from './isFinite'
export { default as isInteger } from './isInteger'
export { default as isNaN } from './isNaN'
export { default as isSafeInteger } from './isSafeInteger'
export { default as parseFloat } from './parseFloat'
export { default as parseInt } from './parseInt'
