// export { first } from '@wareset-utilites/lang/first'
// export { includes } from '@wareset-utilites/lang/includes'
// export { indexOf } from '@wareset-utilites/lang/index-of'
// export { last } from '@wareset-utilites/lang/last'
// export { lastIndexOf } from '@wareset-utilites/lang/last-index-of'
// export { length } from '@wareset-utilites/lang/length'
// export { slice } from '@wareset-utilites/lang/slice'

export { endsWith } from './ends-with'
export { padEnd } from './pad-end'
export { padStart } from './pad-start'
export { repeat } from './repeat'
export { replace } from './replace'
export { startsWith } from './starts-with'
export { toCapitalize } from './to-capitalize'
export { toCodeCamelcase } from './to-code-camelcase'
export { toCodeKebabcase } from './to-code-kebabcase'
export { toCodePascalcase } from './to-code-pascalcase'
export { toCodeSnakecase } from './to-code-snakecase'
export { toLowercase } from './to-lowercase'
export { toUppercase } from './to-uppercase'
export { trim } from './trim'
export { trimLeft } from './trim-left'
export { trimRight } from './trim-right'
